config/routes.rb
Rails.application.routes.draw do
  


  mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  devise_for :users
  get "/" => "home#index", :as => "root"
  get "/contacts" => "home#contact"

  get "/items" => "home#item"
  get "/referee" => "home#referee"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  resources :team, only: [:index, :show]
  resources :table, only: [] do
    member do
      get 'team_position'
      get 'match_result'
      get 'goal_leader'
      get 'summary'
    end    
  end
  resources :photo, only: [:index, :show] do
    # /ost 'show_photo'
  end
  get "/futadmin/generate"=>"futadmin#generate"

  resources :doc do
    member do 
        get 'download'
    end
  end

  resources :history
  
end

app/models/amplua.rb
class Amplua < ApplicationRecord
    has_many :players
    validates_presence_of :name
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/doc.rb
class Doc < ApplicationRecord
    def initialize(params = {})
        file = params.delete(:file)
        super
        if file
            self.filename = sanitize_filename(file.original_filename)
            self.content_type = file.content_type
            self.file_contents = file.read
        end
    end


    private
    def sanitize_filename(filename)
        return File.basename(filename)
    end

    
end

app/models/goal_leader.rb
class GoalLeader < ApplicationRecord
    belongs_to :team
    belongs_to :season
    default_scope {where(season_id: Season.ids)}
    validates_uniqueness_of :fio, scope: [:team_id, :season_id]
    validates_presence_of :fio, :team_id, :season_id, :goal
end

app/models/item.rb
class Item < ApplicationRecord
    #has_attached_file :image
    validates :title, presence: true

    validates :body, presence: true    
    
    default_scope {order(created_at: :desc)}
    
    has_attached_file :image, {:styles => { :small => "150x150>" },
            
    url: "/system/:hash.:extension",
    hash_secret: "dc6360523aa19bd9913d64b7ebc83009c09ab5e48814f713c3027e92bf457b0d70f5f3f8d8ec1adc6450664198dc0090ece075c54eb852def1147e972f9ed64d",
    convert_options: {
                      thumb: "-quality 70 -strip",
                      original: "-quality 90"
                  }
    }
    
    validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 5.megabyte }

    
end

app/models/league.rb
class League < ApplicationRecord
    has_many :teams, dependent: :destroy
    
    has_many :table_result, dependent: :destroy
    belongs_to :season

    default_scope {joins(:season).where('seasons.current is true')}
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :tour
  default_scope {where(tour_id: Tour.all.ids)}  
	has_attached_file :image, {:styles => { :small => "150x150>",:big => "650x650>"},
          
    url: "/system/:hash.:extension",
    hash_secret: "dc6360523aa19bd9913d64b7ebc83009c09ab5e48814f713c3027e92bf457b0d70f5f3f8d8ec1adc6450664198dc0090ece075c54eb852def1147e972f9ed64d",
    convert_options: {
                      thumb: "-quality 70 -strip",
                      original: "-quality 90"
                  }
    }
    
    validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 10.megabyte }

end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :amplua
    belongs_to :team
    default_scope {where(team_id: Team.all.ids)}

    
end

app/models/referee.rb
class Referee < ApplicationRecord
    has_attached_file :image, {:styles => { :small => "150x150>",:big => "650x650>"},
            
    url: "/system/:hash.:extension",
    hash_secret: "dc6360523aa19bd9913d64b7ebc83009c09ab5e48814f713c3027e92bf457b0d70f5f3f8d8ec1adc6450664198dc0090ece075c54eb852def1147e972f9ed64d",
    convert_options: {
                      thumb: "-quality 70 -strip",
                      original: "-quality 90"
                  }
    }
    
    validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 5.megabyte }
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :home_team, :class_name => "Team", :foreign_key => "home_team_id"

    belongs_to :guest_team, :class_name => "Team", :foreign_key => "guest_team_id"
    
    belongs_to :tour
    
    scope :finished, ->{where("result!=''").order(timestamp: :desc)}
    scope :start, ->{where("result=''").order(timestamp: :desc)}
    default_scope {where(tour_id: Tour.all.ids).order(:timestamp)}

end

app/models/season.rb
class Season < ApplicationRecord
	has_many :tours
	has_many :goal_leaders
	scope :current, ->{where(current: true)}
	scope :old, ->{where(current: false)}
	default_scope {order(:id)}
end

app/models/table_result.rb
class TableResult < ApplicationRecord
    belongs_to :league
    belongs_to :team
    # default_scope {where(league_id: League.all.ids)}
    
    

end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :league
    #has_many :teams
    has_many :goal_leaders, dependent: :destroy
    has_many :players, dependent: :destroy
    has_many :table_result, dependent: :destroy
    default_scope {where(league_id: League.ids)}
    #has_many :home_teams, :class_name => "Team", :foreign_key => "home_team_id"
    #has_many :guest_teams, :class_name => "Team", :foreign_key => "guest_team_id"
    
    def schedules
        Schedule.where('home_team_id=? or guest_team_id=?', self.id, self.id)
    end
    
    has_attached_file :image, {:styles => { :small => "150x150>",:big => "650x650>"},
            
    url: "/system/:hash.:extension",
    hash_secret: "dc6360523aa19bd9913d64b7ebc83009c09ab5e48814f713c3027e92bf457b0d70f5f3f8d8ec1adc6450664198dc0090ece075c54eb852def1147e972f9ed64d",
    convert_options: {
                      thumb: "-quality 70 -strip",
                      original: "-quality 90"
                  }
    }
    
    validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 7.megabyte }
    
    def count_games
        at_home_schedule = Schedule.finished.where(home_team_id: self.id)
        at_guest_schedule = Schedule.finished.where(guest_team_id: self.id)
        counter_all=counter_win = counter_lost=counter_pat = counter_ball_create=counter_ball_lost= 0
				counter_all=at_home_schedule.count+at_guest_schedule.count				
        at_home_schedule.each do |s|					
					home_goal = s.result.split(':')[0]
					guest_goal = s.result.split(':')[1]
					counter_ball_create = counter_ball_create+home_goal.to_i
					counter_ball_lost = counter_ball_lost+guest_goal.to_i
					home_goal.to_i>guest_goal.to_i ? counter_win+=1 : home_goal.to_i<guest_goal.to_i ? counter_lost+=1 : counter_pat+=1
				end
				
				at_guest_schedule.each do |s|					
					home_goal = s.result.split(':')[0]
					guest_goal = s.result.split(':')[1]
					counter_ball_create = counter_ball_create+guest_goal.to_i
					counter_ball_lost = counter_ball_lost+home_goal.to_i
					
					home_goal.to_i<guest_goal.to_i ? counter_win+=1 : home_goal.to_i>guest_goal.to_i ? counter_lost+=1 : counter_pat+=1
				end
				return counter_all, counter_win, counter_pat, counter_lost,counter_ball_create,counter_ball_lost
				
    end
		
		

   
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_many :schedules
    has_many :photos
    belongs_to :season

    default_scope {joins(:season).where('seasons.current is true')}
   


    def self.current_tours
    	Tour.where("tours.name !~*'финал'")
    end
    def self.final_tours
    	Tour.where("tours.name ~*'финал' and tours.name !~*'1/'").pluck(:id)
    end

    def self.third_tours
        Tour.where("tours.name ~*'3 место'").pluck(:id)
    end

    def self.semifinal_tours
    	Tour.where("tours.name ~*'полу'").pluck(:id)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
          :rememberable, :validatable, :registerable
end

app/helpers/doc_helper.rb
module DocHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 
      = if content_for?(:title) then yield(:title) + ' | ' end
      Официальный сайт комитета по футзалу Карагандинской областной ассоциации футбола
    %meta{:content => "#{yield_meta_tag(:description, 'официальный сайт карагандинской областной ассоциации футбола, на котором размещена информация о проходящих встречах, выложено расписание игр и их итоги, размещена информация о командах, принимающих участвие в турнире')}", :name => "description"}
    %meta{:content => "#{yield_meta_tag(:keywords, 'футзал, караганда, таблица, игра, расписания, встреча, 2018')}", :name => "keywords"}

    %meta{name:"author", content: 'Proshakova Maria'}
    %meta{name:"copyright", content: 'Все права принадлежат комитету по футзалу Карагандинской областной ассоциации футбола'}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{name: "yandex-verification", content: 'bf77ed3c168a83ba'}
    =favicon_link_tag 'favicon.ico'

    
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      .content
        =render 'share/label_bar'
        =render 'share/topbar'


        .row
          .col-md-10.col-md-offset-1
            = yield
        =render 'share/footer'
    
:javascript
    $(window).scroll(function () {
        if ($(this).scrollTop() > 300) {
        
            $('#scroller').fadeIn();
            $('.my_menu').animate({"position": "fixed", "top": "0"},500);
        } else {
            $('#scroller').fadeOut();
            $('.my_menu').removeClass('positionTop');
            }
    });


    $('#scroller').click(function () {
        $('body,html').animate({
            scrollTop: 0
        }, 400);
        return false;
    });

  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter51124184 = new Ya.Metrika2({
                  id:51124184,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/tag.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks2");
%noscript
  %div
    %img{:alt => "", :src => "https://mc.yandex.ru/watch/51124184", :style => "position:absolute; left:-9999px;"}/
    / /Yandex.Metrika counter

app/views/share/_footer.haml
.footer
  -#.row
    .col-md-12
  -#.text-center
    %a{:href => "https://fifa.com", target: :blank, title: 'Переход на официальный сайт FIFA'}
      =image_tag("fifa.png", size: "55")


    %a{:href => "https://uefa.com", target: :blank, title: 'Переход на официальный сайт UEFA'}
      =image_tag("uefa.png", size: "55")

    %a{:href => "https://koaf.kz", target: :blank, title: 'Переход на официальный сайт КОАФ'}
      =image_tag("koaf.png", size: "55")

  .row
    -#.col-md-12
    .text-center.copyright
      \&#xA9; 2019 -
      =Date.today.year
      Все права защищены. Копирование допускается с указанием на первоисточник.

app/views/share/_label_bar.haml
#label_bar
  .row
    .col-md-8
      .pull-left
        %a{:href => "/", title: 'На главную'}
          =image_tag("brand.png", size: "75", class: 'brand')
        Комитет по футзалу Карагандинской областной ассоциации футбола

    .col-md-4
      .well.pull-right

        =image_tag("sponsor1.png", size: "60", title: "Мини-футбольный клуб 'Тулпар'")
        =image_tag("sponsor3.png", height: "55",width:"110", title: "KAZ GLOBAL TRAVEL")
        =image_tag("sponsor2.png", size: "60", title: "Спорткомплекс 'Тулпар'")

app/views/share/_social_share.haml
%script{:src => "//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"}
%script{:src => "//yastatic.net/share2/share.js"}
.ya-share2{"data-services" => "collections,vkontakte,facebook,odnoklassniki,moimir"}

app/views/share/_topbar.haml
#custom-bootstrap-menu.navbar.navbar-default.my_menu{:role => "navigation"}
  #scroller.pull-right
  .navbar-header
    %a.navbar-brand{:href => "#"}

    %button.navbar-toggle{"data-target" => ".navbar-menubuilder", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
  .collapse.navbar-collapse.navbar-menubuilder
    %ul.nav.navbar-nav.navbar-left
      %li{class: request.path==root_path ? 'active':''}
        =link_to root_path do
          %i.fa.fa-home
          Главная
      %li{class: request.path.match('doc') ? 'active':''}
        =link_to doc_index_path do
          %i.fa.fa-book
          Документы
      %li{class: request.path==referee_path ? 'active':''}
        =link_to referee_path do
          %i.fa.fa-id-badge
          Судьи
      -if League.count>0&&Team.where(league_id: League.ids).count>0
        %li.dropdown{class: (request.path.match('team')&&!request.path.match('table')) ? 'active':''}
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-futbol-o
            Команды
            %span.caret
          %ul.dropdown-menu            
            -League.all.each do |l|
              %li
                %a{:href => team_index_path(league_id: l.id)} Текущий сезон. #{l.name}
            -League.unscoped.where(season_id: Season.unscoped.old.pluck(:id)).each do |l|
              %li
                %a{:href => team_index_path(league_id: l.id)} Архив. Сезон #{l.season.name}. #{l.name}

      -if League.count>0&&Team.where(league_id: League.ids).count>0
        %li.dropdown{class: request.path.match('table')&&params[:old].blank? ? 'active':''}
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-table
            Таблицы
            %span.caret
          %ul.dropdown-menu
            -League.all.each do |l|
              %li
                %a{:href => team_position_table_path(l.id)}=l.name


      -history_seasons = Season.unscoped.where(current: false)
      -if history_seasons.present?  || Photo.all.count>0 
        %li.dropdown{class: request.path.match('phot').present? ? 'active':''}
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-table
            Фото
            %span.caret
          %ul.dropdown-menu
            -if  Photo.all.count>0  
              %li
                %a{:href => photo_index_path} Текущий сезон
            -history_seasons.all.each do |h|
              %li
                %a{:href => photo_index_path(old: true, season_id: h.id)}
                  Архив #{h.name}
          
          
      -if history_seasons.present? && League.unscoped.where(season_id: history_seasons.pluck(:id)).present?
        %li.dropdown{class: params[:old].present?&&request.path.match('team_position').present? ? 'active':''}
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-table
            Архив игр
            %span.caret
          %ul.dropdown-menu
            -history_seasons.all.each do |h|
              -League.unscoped.where(season_id: h.id).each do |l|
                %li
                  %a{:href => team_position_table_path(id: l.id, old: true)}
                    =h.name
                    =l.name

      %li{class: request.path==contacts_path ? 'active':''}
        =link_to "https://www.youtube.com/playlist?list=PLONkxaSIBkRNyT-9qUbkkF6QZC4lRItNM",target: "_blank" do
          %i.fa.fa-youtube-play
          Просмотр матчей
          
    %ul.nav.navbar-nav.navbar-right
      %li
        %a{:href => "https://fifa.com", target: :blank, title: 'Переход на официальный сайт FIFA'}
          =image_tag("fifa.png", size: "35")
      %li
        %a{:href => "https://uefa.com", target: :blank, title: 'Переход на официальный сайт UEFA'}
          =image_tag("uefa.png", size: "35")
      %li
        %a{:href => "https://koaf.kz", target: :blank, title: 'Переход на официальный сайт КОАФ'}
          =image_tag("koaf.png", size: "35")

      -if user_signed_in?

        %li
          =link_to destroy_user_session_path, :method => :delete, title:'Выйти' do
            %i.fa.fa-sign-out
        -if current_user.active_admin
          %li
            =link_to rails_admin_path, title: 'панель администратора' do
              %i.fa.fa-user-o
      -else
        %li
          =link_to new_user_session_path do
            %i.fa.fa-sign-in