config/routes.rb
Rails.application.routes.draw do
  


  mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  devise_for :users
  get "/" => "home#index", :as => "root"
  get "/contacts" => "home#contact"

  get "/items" => "home#item"
  get "/referee" => "home#referee"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  resources :team, only: [:index, :show]
  resources :table, only: [] do
    member do
      get 'team_position'
      get 'match_result'
      get 'goal_leader'
      get 'summary'
    end    
  end
  resources :photo, only: [:index, :show] do
    # /ost 'show_photo'
  end
  get "/futadmin/generate"=>"futadmin#generate"

  resources :doc do
    member do 
        get 'download'
    end
  end

  resources :history
  
end

app/controllers/home_controller.rb
require 'date'
class HomeController < ApplicationController
  def index
      @items =Item.last(3)
      # leagues = League.all()
      # leaders = GoalLeader.select("teams.league_id as league_id, max(goal_leaders.goal) as max_goal").joins(:team).where("teams.league_id in (?)", leagues.pluck(:id)).group("teams.league_id")
      
      # max_goals = {}
      # for res in leaders
      #   max_goals[res.league_id] = res.max_goal
      # end
      # puts(max_goals)
      # lead = GoalLeader.select("leagues.name as league, leagues.id as league_id, fio, goal").joins('join teams on teams.id = goal_leaders.team_id join leagues on leagues.id = teams.league_id').where("goal in (?) and teams.league_id in (?)", max_goals.values, max_goals.keys).order("league")
      # @all_leaders = []
      # for res in lead
      #   if max_goals[res.league_id] == res.goal          
      #     @all_leaders << res
      #   end
      # end

      @last_games = Schedule.where("timestamp between ? AND ?", Date.today - 7, Date.today)
      @future_games = Schedule.where("timestamp between ? AND ? or timestamp is null", Date.today+1, Date.today + 30)
      @current_games = Schedule.where("timestamp between ? AND ?", Date.today, Date.today+1)
       
  end
  def contact
      @text = Contact.all
  end

  def referee
      @text = Referee.all
  end
  def item
      @items = Item.last(20)
  end
  
  def table_result
      if current_user.present? && current_user.active_admin
          @table_result = TableResult.where(league_id: League.first.id).order(:place)
      end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_games.haml
.panel.panel-success
  .panel-heading
    =name
  .panel-body
    %ul.list-group
      %table.table.table-hover.table-condensed.table-striped.table-sm

        -games.each do |result|
          =render 'list', result: result

app/views/home/_list.haml
%tr
  %td
    -if result.timestamp.present?
      %strong=l result.timestamp, format: :short
      
    -else
      Не указано

  %td.text-left
    -if result.home_team.present?
      =result.home_team.name


      %br
      %br
        =result.guest_team.name
  %td  
    -if result.result.present?
      
      %strong
        .text-center
          =result.result.split(':')[0]
          -if result.guest_team.present?
            - length = result.home_team.name.length
            %br
            -if length >24
              #content2
            -if result.home_team.id == 121 || length > 34
              #content2
          
            %br=result.result.split(':')[1]



  

app/views/home/contact.html.haml
- title 'Контакты'
- meta_tag :description, 'Контактные данные КОАФ'
- meta_tag :keywords, 'КОАФ контакт'
.panel.panel-success
  .panel-heading
    .row
      .col-md-9
        Контактная информация
      .col-md-3
        =render 'share/social_share'
  .panel-body
    -if @text.present?
      -@text.each do |c|
        %p=c.body
    -else
      .text-center Пока не создано ни одной записи о контактах

app/views/home/index.html.haml
- title 'Главная'
- meta_tag :description, 'Расписание следующего тура, итоги прошедшего тура, новости соревнований по футзалу Карагандинской области 2018-2019'
- meta_tag :keywords, 'Футзал, Караганда, Карагандинская область, 2021-2022 год, расписание игр футзал'

-if @items.present?
  .panel.panel-success
    .panel-heading
      Новости
    .panel-body    
      %ul.list-group
        -@items.each do |item|
          %li.list-group-item
            
            .row
              .col-md-3
                              
                .text-center
                  .photo_large
                    = image_tag item.image.url(:small) if item.image.present?
              .col-md-9


                %h3.text-center=link_to item.title, items_path(item), target: :blank

                %p=item.body.html_safe

                %p.pull-right
                  %i.fa.fa-calendar
                  =l item.updated_at+6.hours, format: :short

- if @current_games.present?
  =render 'games', name: "Игры сегодня", games: @current_games

- if @future_games.present?
  =render 'games', name: "Расписание предстоящих игр", games: @future_games

- if @last_games.present?
  =render 'games', name: "Результаты игр прошедшей недели", games: @last_games

app/views/home/item.haml
- title 'Новости'
- meta_tag :description, 'Новости соревнований по футзалу Карагандинской области 2018-2019'
- meta_tag :keywords, 'Новости, Футзал, Караганда, Карагандинская область, 2018 год, '+"#{@league_name}"
.panel.panel-success
  .panel-heading
    .row
      .col-md-9
        Новости
      .col-md-3
        =render 'share/social_share'
  .panel-body
    -if @items.present?
      %ul.list-group
        -@items.each do |item|
          %li.list-group-item
            
            .row
              .col-md-3

                .text-center= image_tag item.image.url(:small) if item.image.present?
              .col-md-9
                %h3.text-center=link_to item.title, items_path(item), target: :blank
                %p=item.body.html_safe
                .pull-right
                  %i.fa.fa-calendar
                  =l item.updated_at+6.hours, format: :short

app/views/home/referee.html.haml
- title 'Судьи'
- meta_tag :description, 'Судейская коллегия соревнований по футзалу Карагандинской области 2018-2019'
- meta_tag :keywords, 'Судьи, судейская коллегия, футзал, Караганда, Карагандинская область, 2018 год, расписание игр футзал'
.panel.panel-success
  .panel-heading
    Судейская коллегия
  .panel-body
    -if @text.present?
      -@text.each_with_index do |c, index|
        .photo
          #{image_tag c.image.url(:big) if c.image.present?} 
          =image_tag("no_foto.jpg") unless c.image.exists?
          %figcaption
            #{c.fio if c.fio.present?},
            #{c.city if c.city.present?},
            #{c.category if c.category.present?}
            #{c.comment if c.comment.present?}

app/views/home/table_result.haml
456456456 