config/routes.rb
Rails.application.routes.draw do
  


  mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  devise_for :users
  get "/" => "home#index", :as => "root"
  get "/contacts" => "home#contact"

  get "/items" => "home#item"
  get "/referee" => "home#referee"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  resources :team, only: [:index, :show]
  resources :table, only: [] do
    member do
      get 'team_position'
      get 'match_result'
      get 'goal_leader'
      get 'summary'
    end    
  end
  resources :photo, only: [:index, :show] do
    # /ost 'show_photo'
  end
  get "/futadmin/generate"=>"futadmin#generate"

  resources :doc do
    member do 
        get 'download'
    end
  end

  resources :history
  
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :league
    #has_many :teams
    has_many :goal_leaders, dependent: :destroy
    has_many :players, dependent: :destroy
    has_many :table_result, dependent: :destroy
    default_scope {where(league_id: League.ids)}
    #has_many :home_teams, :class_name => "Team", :foreign_key => "home_team_id"
    #has_many :guest_teams, :class_name => "Team", :foreign_key => "guest_team_id"
    
    def schedules
        Schedule.where('home_team_id=? or guest_team_id=?', self.id, self.id)
    end
    
    has_attached_file :image, {:styles => { :small => "150x150>",:big => "650x650>"},
            
    url: "/system/:hash.:extension",
    hash_secret: "dc6360523aa19bd9913d64b7ebc83009c09ab5e48814f713c3027e92bf457b0d70f5f3f8d8ec1adc6450664198dc0090ece075c54eb852def1147e972f9ed64d",
    convert_options: {
                      thumb: "-quality 70 -strip",
                      original: "-quality 90"
                  }
    }
    
    validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 7.megabyte }
    
    def count_games
        at_home_schedule = Schedule.finished.where(home_team_id: self.id)
        at_guest_schedule = Schedule.finished.where(guest_team_id: self.id)
        counter_all=counter_win = counter_lost=counter_pat = counter_ball_create=counter_ball_lost= 0
				counter_all=at_home_schedule.count+at_guest_schedule.count				
        at_home_schedule.each do |s|					
					home_goal = s.result.split(':')[0]
					guest_goal = s.result.split(':')[1]
					counter_ball_create = counter_ball_create+home_goal.to_i
					counter_ball_lost = counter_ball_lost+guest_goal.to_i
					home_goal.to_i>guest_goal.to_i ? counter_win+=1 : home_goal.to_i<guest_goal.to_i ? counter_lost+=1 : counter_pat+=1
				end
				
				at_guest_schedule.each do |s|					
					home_goal = s.result.split(':')[0]
					guest_goal = s.result.split(':')[1]
					counter_ball_create = counter_ball_create+guest_goal.to_i
					counter_ball_lost = counter_ball_lost+home_goal.to_i
					
					home_goal.to_i<guest_goal.to_i ? counter_win+=1 : home_goal.to_i>guest_goal.to_i ? counter_lost+=1 : counter_pat+=1
				end
				return counter_all, counter_win, counter_pat, counter_lost,counter_ball_create,counter_ball_lost
				
    end
		
		

   
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
      @teams = Team.unscoped.where(league_id: params[:league_id]).order(:name)
  end

  def show
      @team = Team.unscoped.find(params[:id])
      @league_name=League.unscoped.find(@team.league_id).name
      
      @players = @team.players
      @result = TableResult.unscoped.find_by_team_id(params[:id])
      @goal_leaders = GoalLeader.unscoped.where(team_id: params[:id])

  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/team/index.html.haml
-league_name = League.unscoped.find(params[:league_id]).name
- title 'Команды '+"#{league_name}"
- meta_tag :description, 'Команды, принимающие участие в соревнованиях по футзалу Карагандинской области 2021-2022'
- meta_tag :keywords, 'Команды, футзал, Караганда, Карагандинская область, 2021 год, расписание игр футзал, '+"#{league_name}"
.panel.panel-success
  .panel-heading
    .row
      .col-md-9
        Команды. #{league_name}.

      .col-md-3
        =render 'share/social_share'
  .panel-body
    -@teams.each do |t|
      .photo
        =link_to   team_path(t.id), target: :blank, title: 'Перейти на страницу команды' do
          #{image_tag t.image.url(:big) if t.image.exists?}
          =image_tag("no_foto.jpg") unless t.image.exists?
          %figcaption=t.name

app/views/team/show.html.haml
- title "#{@team.name}. #{@league_name}"
- meta_tag :description, "#{@team.name}. #{@league_name}. Участник соревнований по футзалу Карагандинской области 2021-2022"
- meta_tag :keywords, "#{@team.name} , Футзал, Караганда, Карагандинская область, 2021 год, "+"#{@league_name}"

.panel.panel-success
  .panel-heading
    .row
      .col-md-12
        .row
          .col-md-9
            #{@team.name}. #{@league_name}
          
          .col-md-3
            =render 'share/social_share'
  .panel-body 
        
    - if @team.sponsor.present?  
      .row
        .col-md-12
          %h4.text-right
            Спонсор команды:  
            =link_to @team.sponsor, @team.sponsor, target: "_blank" 

    .row
      .col-md-12
        .text-center 
          .photo_large
            =link_to  @team.image.url(:original, false), target: :blank do
              #{image_tag @team.image.url(:big) if @team.image.present?}

    
    .row
      .col-md-6  
        .team-well  
          -if @players.present?
            %h3
              %i.fa.fa-male 
              Состав команды:
            -@players.each_with_index  do |p,i|
              %p
                #{i+1}. #{p.fi}
                -if p.year.present?
                  (#{p.year})
                , #{p.amplua.name}
                / -if GoalLeader.find_by_player_id(p.id).present?

          -else
            .text-center состав не указан
      .col-md-6
        
        -if @result.present?
          .team-well 
            %h3 
              %i.fa.fa-table
              Турнирное положение на #{Time.now.strftime('%d.%m.%Y')}:
            %p Сыграно матчей: #{@result.count_game}
            %p Выигрыш: #{@result.count_win}
            %p Ничья: #{@result.count_pat}
            %p Поражение: #{@result.count_lost}
            %p Забито мячей: #{@result.count_ball_create}
            %p Пропущено мячей: #{@result.count_ball_lost}
            %p Разница мячей:  #{@result.sub_ball}
            %p Место:  #{@result.place}
        -if @goal_leaders.present?
          %br
          .team-well 
            %h3
              %i.fa.fa-futbol-o
              Бомбардиры турнира
            -@goal_leaders.each_with_index do |l,i|
              %p
                #{i+1}.
                =l.fio
                =l.goal
                голов