config/routes.rb
Rails.application.routes.draw do
  


  mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  devise_for :users
  get "/" => "home#index", :as => "root"
  get "/contacts" => "home#contact"

  get "/items" => "home#item"
  get "/referee" => "home#referee"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #mount RailsAdmin::Engine => '/fadmin', as: 'rails_admin'
  resources :team, only: [:index, :show]
  resources :table, only: [] do
    member do
      get 'team_position'
      get 'match_result'
      get 'goal_leader'
      get 'summary'
    end    
  end
  resources :photo, only: [:index, :show] do
    # /ost 'show_photo'
  end
  get "/futadmin/generate"=>"futadmin#generate"

  resources :doc do
    member do 
        get 'download'
    end
  end

  resources :history
  
end

app/models/doc.rb
class Doc < ApplicationRecord
    def initialize(params = {})
        file = params.delete(:file)
        super
        if file
            self.filename = sanitize_filename(file.original_filename)
            self.content_type = file.content_type
            self.file_contents = file.read
        end
    end


    private
    def sanitize_filename(filename)
        return File.basename(filename)
    end

    
end

app/controllers/doc_controller.rb
class DocController < ApplicationController
  before_action :check_admin, only: [:create, :destroy]
    def index
      @documents = Doc.order(:created_at).where('schedule_id is null')

  end

  def download
      @document=Doc.find(params[:id])
      send_data(@document.file_contents,
            type: @document.content_type,
            filename: @document.filename)
      # redirect_to doc_index_path
  end

  def create
    if params[:attachments].present?
      params[:attachments].each do |file|
        filename = File.basename(file.original_filename)
        content_type = file.content_type
        file_contents = file.read
        Doc.create(filename: filename,
                        content_type: content_type,
                        file_contents: file_contents,
                        schedule_id: params[:schedule_id].present? ? params[:schedule_id] :'' )
      end
      if params[:schedule_id].present?
        redirect_to summary_table_path(params[:league_id])
      else
        redirect_to doc_index_path
      end

    else
      redirect_to doc_index_path,  notice: 'Файлы не выбраны'
    end
  end

  def destroy
      doc = Doc.find(params[:id])
      schedule_id = doc.schedule_id
      doc.destroy
      if schedule_id.present?
        league_id = Schedule.find(schedule_id).home_team.league_id
        redirect_to summary_table_path(league_id)
      else
        redirect_to doc_index_path
      end


  end
  private 
  def document_params
   params.require(:doc).permit(:file)
  end
  def check_admin
     redirect_to doc_index_path unless current_user.present? && current_user.active_admin
  end
end

app/controllers/futadmin/doc_controller.rb
class Futadmin::DocController < FutadminController
  def new
      @document = Doc.new
  end

  def create
       @document = Doc.create
  end

  def show
      send_data(@document.file_contents,
            type: @document.content_type,
            filename: @document.filename)
  end
  private
  def document_params
    params.require(:doc).permit(:file)
  end
end

app/helpers/doc_helper.rb
module DocHelper
end

app/helpers/futadmin/doc_helper.rb
module Futadmin::DocHelper
end

app/views/doc/create.html.haml
%h1 Doc#create
%p Find me in app/views/doc/create.html.haml

app/views/doc/delete.html.haml
%h1 Doc#delete
%p Find me in app/views/doc/delete.html.haml

app/views/doc/download.html.haml
%h1 Doc#download
%p Find me in app/views/doc/download.html.haml

app/views/doc/index.html.haml
- title 'Документы'
- meta_tag :description, 'Положение игр и другие документы соревнований по футзалу Карагандинской области 2018-2019'
- meta_tag :keywords, 'Документы, положение игр, футзал, Караганда, Карагандинская область, 2018 год, расписание игр футзал'
.panel.panel-success
  .panel-heading
    .row
      .col-md-9
        Документы
      .col-md-3
        =render 'share/social_share'
  .panel-body
    -if current_user.present? && current_user.active_admin 
      = form_tag doc_index_path, method: :post, multipart: true do
        =file_field_tag :file, :multiple => true, name: "attachments[]"
        = submit_tag 'загрузить'

    -@documents.each_with_index do |d,i|
      %p
        #{i+1}.
        
        =link_to d.filename, download_doc_path(d.id), title: 'скачать'
        -if current_user.present? && current_user.active_admin
          =link_to doc_path(d), method: :delete, data: {confirm:'Удалить документ?'}, title: 'удаление' do
            %i.fa.fa-trash